server:
  port: 8888
  
spring:
  profiles:
    active: native # file system에서 Config file을 읽어 올 수 있도록 native profile을 활성화시켜야 한다.
  
  application:
    name: msa-architecture-config-server
    
---
 
spring:
  profiles: native
  cloud:
    config:
      server:
        native:
          search-locations: file:///C:/eclipseProjects/msa-architecture-config-server/conf # config file의 위치, 윈도우의 경우 "/"가 추가로 필요하다.
          #search-locations: file://${user.home}/eclipseProjects/msa-architecture-config-server/conf # config file의 위치, 윈도우의 경우 "/"가 추가로 필요하다.

---

spring:
  cloud:
    config:
      server:
        git: 
          uri: https://github.com/architectstory/msa.git