msaconfig:
  greeting: "hello"
  
---

spring:
  profiles: local

msaconfig:
  greeting: "welcome to local server(native)"

---

spring:
  profiles: dev

msaconfig:
  greeting: "welcome to dev server(native)"

---

spring:
  profiles: test
  
msaconfig:
  greeting: "welcome to test server(native)"

---

spring:
  profiles: staging
  
msaconfig:
  greeting: "welcome to staging server(native)"

---

spring:
  profiles: prod
  
msaconfig:
  greeting: "welcome to prod server(native)"